replicaCount: 1

snowflake:
  config:
    default_fetch_interval: 600
    metrics:
      - name: STORAGE_USAGE
        help: storage usage in bytes
        statement: SELECT STAGE_BYTES, STORAGE_BYTES FROM snowflake.account_usage.storage_usage WHERE usage_date >= DATEADD('DAYS',-7,CURRENT_DATE()) ORDER BY usage_date;

image:
  repository: cbellew/snowflake-prometheus-exporter
  tag: 1.0.0
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true

service:
  label: app-snowflake-prometheus
  type: ClusterIP
  port: 80

ingress:
  enabled: false

securityContext:
  runAsUser: 65534
  runAsNonRoot: true
  runAsGroup: 65534

#securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
